config/routes.rb
Rails.application.routes.draw do
  
  get 'components/index'
  get "elements/form"
  get "elements/sum"
  resources :elements
  
  get "baums/form"
  get "baums/sum"
  resources :baums
  root 'welcome#index'
  
  devise_for :users
  resources :form do
    resources :component
  end
  #resources :welcome
  #get 'welcome/index'
  #get "welcome/sum"
  
  #root "elements#form"


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/element.rb
class Element < ActiveRecord::Base
  resourcify

end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  before_filter :authenticate_user!, :except => [:form, :sum]
  load_and_authorize_resource
  
  def index
    @elements = Element.all
  end
  
  def new
    @element = Element.new
  end
  
  def show
  end
  
  def edit
  end
  
  def create
    @element = Element.new(element_params)
    
    if @element.save
      redirect_to elements_path
    else
      render 'new'
    end
  end
    
  def update
    if @element.update(element_params)
      redirect_to elements_path
    else
      render 'edit'
    end
  end
  
  def destroy
    @element = Element.find(params[:id])
    @element.destroy
    
    redirect_to elements_path
  end
  
  def form
  end
    
  #####################################################
  #####################################################
  #####################################################
    
  def sum
    @hh = [];
    temp = Element.new 
    @sum = 0;
    
    if params[:archproject].to_f > 0
      @sum = @sum + Element.find_by(label: :archproject).price
    end
    
    
    if params[:plfund].to_f > 0
      temp = Element.find_by(label: :plfund)
      @sum = @sum + temp.price * params[:plfund].to_f;
      @hh.push({"name" => temp.name.to_s, "value" => temp.price * params[:plfund].to_f})
    end
        
    
    
    #steny
    if params[:plsten].to_f > 0
      if params[:sip160]
        temp = Element.find_by(label: :sip160)
        @sum = @sum + temp.price * params[:plsten].to_f
        @hh.push({"name" => temp.name, "value" => temp.price * params[:plsten].to_f})
      end
       if params[:karkas150]
        temp = Element.find_by(label: :karkas150)
        @sum = @sum + temp.price * params[:plsten].to_f
        @hh.push({"name" => temp.name, "value" => temp.price * params[:plsten].to_f})
          if params[:utiplenie]
            temp = Element.find_by(label: :utiplenie)
            @sum = @sum + temp.price * params[:plsten].to_f
            @hh.push({"name" => temp.name, "value" => temp.price * params[:plsten].to_f})
          end
        end
      if params[:saiding]
        temp = Element.find_by(label: :saiding)
        @sum = @sum + temp.price * params[:plsten].to_f
        @hh.push({"name" => temp.name, "value" => temp.price * params[:plsten].to_f})
      end
      if params[:blockhaus]
        temp = Element.find_by(label: :blockhaus)
        @sum = @sum + temp.price * params[:plsten].to_f
        @hh.push({"name" => temp.name, "value" => temp.price * params[:plsten].to_f})
      end
      if params[:shtukat]
        temp = Element.find_by(label: :shtukat)
        @sum = @sum + temp.price * params[:plsten].to_f
        @hh.push({"name" => temp.name, "value" => temp.price * params[:plsten].to_f})
      end
      if params[:vagonka]
        temp = Element.find_by(label: :vagonka)
        @sum = @sum + temp.price * params[:plsten].to_f
        @hh.push({"name" => temp.name, "value" => temp.price * params[:plsten].to_f})
      end
      if params[:gips]
        temp = Element.find_by(label: :gips)
        @sum = @sum + temp.price * params[:plsten].to_f
        @hh.push({"name" => temp.name, "value" => temp.price * params[:plsten].to_f})
      end
    end
    
   
    


    
        
        
    
    #vnutren peregorodki
    if params[:plvnper].to_f > 0
      if params[:sip120]
        temp = Element.find_by(label: :sip120)
        @sum = @sum + temp.price * params[:plvnper].to_f
        @hh.push({"name" => temp.name, "value" => temp.price * params[:plvnper].to_f})
      end
      if params[:karkas90]
        temp = Element.find_by(label: :karkas90)
        @sum = @sum + temp.price * params[:plvnper].to_f
        @hh.push({"name" => temp.name, "value" => temp.price * params[:plvnper].to_f})
      end
      if params[:vagonkaperegorodka]
        temp = Element.find_by(label: :vagonkaperegorodka)
        @sum = @sum + temp.price * params[:plvnper].to_f * 2;
        @hh.push({"name" => temp.name, "value" => temp.price * params[:plvnper].to_f * 2})
      end
      if params[:gipsperegorodka]
        temp = Element.find_by(label: :gipsperegorodka)
        @sum = @sum + temp.price * params[:plvnper].to_f * 2;
        @hh.push({"name" => temp.name, "value" => temp.price * params[:plvnper].to_f * 2})
      end
      if params[:utiplenie100]
        temp = Element.find_by(label: :utiplenie100)
        @sum = @sum + temp.price * params[:plvnper].to_f
        @hh.push({"name" => temp.name, "value" => temp.price * params[:plvnper].to_f})
      end
    end
    
    
    #potolok
    if params[:plpot].to_f > 0
      if params[:vagonkapot]
        temp = Element.find_by(label: :vagonkapot)
        @sum = @sum + temp.price * params[:plpot].to_f
        @hh.push({"name" => temp.name, "value" => temp.price * params[:plpot].to_f})
      end
      if params[:gipspot]
        temp = Element.find_by(label: :gipspot)
        @sum = @sum + temp.price * params[:plpot].to_f
        @hh.push({"name" => temp.name, "value" => temp.price * params[:plpot].to_f})
      end
    end
    
    
    #perekrytie
    if params[:plper].to_f > 0
      temp = Element.find_by(label: :perekosb)
      @sum = @sum + temp.price * params[:plper].to_f
      @hh.push({"name" => temp.name, "value" => temp.price * params[:plper].to_f})
      if params[:utiplenieper]
        temp = Element.find_by(label: :utiplenieper)
        @sum = @sum + temp.price * params[:plper].to_f
        @hh.push({"name" => temp.name, "value" => temp.price * params[:plper].to_f})
      end
    end
    
    
    #krovlia
    if params[:plkrov].to_f > 0
      temp = Element.find_by(label: :krovlia)
      @sum = @sum + temp.price * params[:plkrov].to_f
      @hh.push({"name" => temp.name, "value" => temp.price * params[:plkrov].to_f})
    
      if params[:bitumkrov]
        temp = Element.find_by(label: :bitumkrov)
        @sum = @sum + temp.price * params[:plkrov].to_f
        @hh.push({"name" => temp.name, "value" => temp.price * params[:plkrov].to_f})
      end
      if params[:metkrov]
        temp = Element.find_by(label: :metkrov)
        @sum = @sum + temp.price * params[:plkrov].to_f
        @hh.push({"name" => temp.name, "value" => temp.price * params[:plkrov].to_f})
      end
      if params[:utipleniekrov]
        temp = Element.find_by(label: :utipleniekrov)
        @sum = @sum + temp.price * params[:plkrov].to_f
        @hh.push({"name" => temp.name, "value" => temp.price * params[:plkrov].to_f})
      end
      
    end
    
    
    
      
      
    #dver
    if params[:dver]
      temp = Element.find_by(label: :dver)
      @sum = @sum + temp.price
      @hh.push({"name" => temp.name, "value" => temp.price})
    end
    if params[:plokna].to_f > 0
      temp = Element.find_by(label: :plokna)
      @sum = @sum + temp.price * params[:plokna].to_f
      @hh.push({"name" => temp.name, "value" => temp.price * params[:plokna].to_f})
    end
    
    
    
    #inzheneria
    if params[:elektrik]
      temp = Element.find_by(label: :elektrik)
      @sum = @sum + temp.price
      @hh.push({"name" => temp.name, "value" => temp.price})
    end
    if params[:vodoprovod]
      temp = Element.find_by(label: :vodoprovod)
      @sum = @sum + temp.price
      @hh.push({"name" => temp.name, "value" => temp.price})
    end
    if params[:kanalis]
      temp = Element.find_by(label: :kanalis)
      @sum = @sum + temp.price
      @hh.push({"name" => temp.name, "value" => temp.price})
    end
    if params[:otoplenie]
      temp = Element.find_by(label: :otoplenie)
      @sum = @sum + temp.price
      @hh.push({"name" => temp.name, "value" => temp.price})
    end
      
      
    
    
    #marketing
    if !(@sum == 0)
      @sum = @sum + Element.find_by(label: :marketing).price
      @sum = @sum + Element.find_by(label: :logistika).price
      if params[:akcionka]
        @sum = @sum + Element.find_by(label: :akcionka).price
      end
      if params[:regional]
        @sum = @sum + Element.find_by(label: :regional).price
      end
      
      
      
      if @sum >= Element.find_by(label: :sum2).price
        @sum = @sum * Element.find_by(label: :nacenka14).price
      elsif @sum >= Element.find_by(label: :sum1).price
        @sum = @sum * Element.find_by(label: :nacenka15).price
      else
        @sum = @sum * Element.find_by(label: :pribyl).price
      end
      
      
    end
  end

  
  
  private
    def element_params
      params.require(:element).permit(:name, :price, :label)
    end
        
 end

app/helpers/elements_helper.rb
module ElementsHelper
  
end

app/views/elements/edit.html.erb
<%= form_for @element do |f| %>
 
  <p>
    <strong><%= @element.name %></strong>
  </p>
 
 <p>
    Цена:<%= f.text_field :price %>
  </p>
  
   
 <p>
    Название:<%= f.text_field :name %>
  </p>
  
  <p>
    <%= submit_tag "Сохранить" %>
  </p>
<% end %>

app/views/elements/form.html.erb
<h1 class="h1_form">"ЕвроХауз"</h1><br><br>

<%= form_tag("sum", method: :get, class: "form-horizontal", role: "form") do %>
  Архитектурный проект <%= check_box_tag 'archproject' %><br><br>
  <span class="caption">Фундамент</span><br>
  Площадь <%= number_field_tag 'plfund' %> м<sup>2</sup><br><br>
  
  <span class="caption">Тип стен</span><br>
  Площадь <%= number_field_tag 'plsten' %> м<sup>2</sup><br>
  СИП160 <%= check_box_tag 'sip160' %>, Каркас150 <%= check_box_tag 'karkas150' %><br>
  Наружная отделка: Сайдинг <%= check_box_tag 'saiding' %>, БлокХаус <%= check_box_tag 'blockhaus' %>, Штукатурка <%= check_box_tag 'shtukat' %><br>
  Внутренняя отделка: Вагонка <%= check_box_tag 'vagonka' %>, Гипсокартон <%= check_box_tag 'gips' %><br>
  Утепление <%= check_box_tag 'utiplenie' %> (только при каркасном типе стен!!!)<br><br>
  
  <span class="caption">Внутренние перегородки</span><br>
  Площадь <%= number_field_tag 'plvnper'%> м<sup>2</sup><br>
  Тип стен: СИП120 <%= check_box_tag 'sip120' %>, Каркас90 <%= check_box_tag 'karkas90' %><br>
  Отделка: Вагонка <%= check_box_tag 'vagonkaperegorodka' %>, Гипсокартон <%= check_box_tag 'gipsperegorodka' %><br>
  Утепление <%= check_box_tag 'utiplenie100' %> (только при каркасном типе стен!!!)<br><br>
  
  <div><span class="caption">Потолки</span><br>
  Площадь <%= number_field_tag 'plpot' %> м<sup>2</sup><br>
  Отделка потолка: Вагонка <%= check_box_tag 'vagonkapot' %>, Гипсокартон <%= check_box_tag 'gipspot' %>
  </div><br><br>
  
  <span class="caption">Перекрытие</span><br>
  Площадь <%= number_field_tag 'plper' %> м<sup>2</sup><br>
  Утепление <%= check_box_tag 'utiplenieper' %><br><br>
  
  <span class="caption">Кровля</span><br>
  Площадь <%= number_field_tag 'plkrov' %> м<sup>2</sup><br>
  Тип кровли: Битумная <%= check_box_tag 'bitumkrov' %>, Металлочерепица <%= check_box_tag 'metkrov' %><br>
  Утепление <%= check_box_tag 'utipleniekrov' %><br><br>
  
  <span class="caption">Инженерия</span><br>
  Электрика <%= check_box_tag 'elektrik' %><br>
  Отопление <%= check_box_tag 'otoplenie' %><br>
  Водопровод <%= check_box_tag 'vodoprovod' %><br>
  Канализация <%= check_box_tag 'kanalis' %><br><br>
  
  <span class="caption">Проемы</span><br>
  Входная дверь <%= check_box_tag 'dver' %><br>
  Окна, площадь <%= number_field_tag 'plokna'%> м<sup>2</sup><br>
  <br>
  
  
  
  <span class="caption">Акционная наценка</span> <%= check_box_tag 'akcionka' %><br>
  <span class="caption">Региональный проект</span> <%= check_box_tag 'regional' %><br><br>
  
  
  
  <%= submit_tag "Подсчитать стоимость", class: "btn btn-xs btn-info" %>
  <%= link_to 'Очистить форму', elements_form_path, class: "btn btn-xs btn-warning" %><br><br>
    <% if can? :update, Element %>
      <%= link_to 'Перейти в раздел редактирования', elements_path, class: "btn btn-xs btn-info" %>
    <% end %>
<% end %>
<br>
<br>
<br>
<br>

app/views/elements/index.html.erb
<h1>Все составляющие проекта ЕвроХауз</h1>
<%= link_to "Excel", elements_path(format: "xls") %>
<table class="table table-striped table-hover">
  <tr>
    <th><strong>Название</strong></th>
    <th>Цена за м<sup>2</sup> или %</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
  <% @elements.each do |element| %>
    <tr>
      <td><%= element.name %></td>
      <td><%= element.price %> </td>
      <% if can? :read, Element %>
       <td><%= link_to 'Подробно..', element, class: "btn btn-xs btn-info" %></td> 
      <% end %>
      <% if can? :update, Element %>
         <td><%= link_to 'Редактировать', edit_element_path(element), class: "btn btn-xs btn-warning" %></td>
      <% end %>
      <% if can? :destroy, Element %>
         <td><%= link_to 'Удалить!', element_path(element), class: "btn btn-xs btn-danger", 
            method: :delete,
            data: { confirm: 'Вы уверены?' } %></td> 
      <% end %>
    
          
     
    </tr>
  <% end %>
</table>
<br>
<%= link_to 'Добавить новый елемент проекта', new_element_path, class: "btn btn-sm btn-success" %>
<%= link_to 'Перейти к форме', elements_form_path, class: "btn btn-xs btn-primary" %>
<br>
<br>
<br>

app/views/elements/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Price</Data></Cell>
      </Row>
    <% @elements.each do |element| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= element.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= element.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= element.price %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/elements/new.html.erb
<h2>Новый елемент проекта</h2>
<%= form_for @element do |f| %>
 
  <p>
    Название:<%= f.text_field :name %>
  </p>
 
  <p>
    Цена:<%= f.text_field :price %>
  </p>
  
  <p>
    Метка:<%= f.text_field :label %>
  </p> 
  
  <p>
    <%= submit_tag "Создать" %>
  </p>
<% end %>

app/views/elements/show.html.erb
<p>
  <strong>Название:</strong>
  <%= @element.name %>
</p>

<p>
  <strong>Цена:</strong>
  <%= @element.price %>
</p>

<%= link_to 'Изменить', edit_element_path(@element) %>

app/views/elements/sum.html.erb
<br>Стоимость проекта: <%= @sum %> грн. <br>

<div id="result">
  <% if @hh.length > 0 %>
  <h1>Выходные данные проекта</h1>
  <table class="table table-striped table-hover">
    <tr>
      <th><strong>Название</strong></th>
      <th><strong>Стоимость (грн)</strong></th>
    </tr>
    <% @hh.each do |h| %>
      <tr>
        <td><%= h["name"] %></td>
        <td><%= h["value"] %></td>
      </tr>
    <% end %>
  </table><br>
  <% end %>
</div>

app/views/elements/sum.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Название</Data></Cell>
        <Cell><Data ss:Type="String">Цена</Data></Cell>
      </Row>
    <%= @ht.each do |h| %>
      <Row>
        <Cell><Data ss:Type="String"><%= h["name"]  %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= h["value"] %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>