config/routes.rb
Rails.application.routes.draw do
  
  get 'components/index'
  get "elements/form"
  get "elements/sum"
  resources :elements
  
  get "baums/form"
  get "baums/sum"
  resources :baums
  root 'welcome#index'
  
  devise_for :users
  resources :form do
    resources :component
  end
  #resources :welcome
  #get 'welcome/index'
  #get "welcome/sum"
  
  #root "elements#form"


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/baum.rb
class Baum < ActiveRecord::Base
end

app/controllers/baums_controller.rb
class BaumsController < ApplicationController
  before_filter :authenticate_user!, :except => [:form, :sum]
  load_and_authorize_resource
  def index
    @baums = Baum.all
    respond_to do |format|
      format.html
      format.csv { send_data @baums.to_csv }
      format.xls
    end
  end
  
  def new
    @baum = Baum.new
  end
  
  def show
  end
  
  def edit
  end
  
  def create
    @baum = Baum.new(baum_params)
    
    if @baum.save
      redirect_to baums_path
    else
      render 'new'
    end
  end
    
  def update
    if @baum.update(baum_params)
      redirect_to baums_path
    else
      render 'edit'
    end
  end
  
  def destroy
    @baum = Baum.find(params[:id])
    @baum.destroy
    
    redirect_to baums_path
  end
  
  def form
  end
  #####################################################
  #####################################################
  #####################################################
  #####################################################
  #####################################################
  #####################################################
  def sum
  
    temp = Baum.new
    @hh = [];
    @sum = 0;
    
    if params[:archproject].to_f > 0
      @sum = @sum + Baum.find_by(label: :archproject).price
    end

    if params[:plfund].to_f > 0
      @sum = @sum + Baum.find_by(label: :plfund).price * params[:plfund].to_f;
      temp = Baum.find_by(label: :plfund)
      @hh.push({"name" => temp.name, "value" => temp.price * params[:plfund].to_f})
    end
    
    
    #steny
    if params[:plsten].to_f > 0
      if params[:dikii]
        if params[:dikii200]
          temp = Baum.find_by(label: :dikii200)
          @sum = @sum + temp.price * params[:plsten].to_f
          @hh.push({"name" => temp.name, "value" => temp.price * params[:plsten].to_f})
        end
        if params[:dikii240]
          temp = Baum.find_by(label: :dikii240)
          @sum = @sum + temp.price * params[:plsten].to_f
          @hh.push({"name" => temp.name, "value" => temp.price * params[:plsten].to_f})
        end
        if params[:dikii260]
          temp = Baum.find_by(label: :dikii260)
          @sum = @sum + temp.price * params[:plsten].to_f
          @hh.push({"name" => temp.name, "value" => temp.price * params[:plsten].to_f})
        end
        if params[:dikii300]
          temp = Baum.find_by(label: :dikii300)
          @sum = @sum + temp.price * params[:plsten].to_f
          @hh.push({"name" => temp.name, "value" => temp.price * params[:plsten].to_f})
        end
        if params[:dikii400]
          temp = Baum.find_by(label: :dikii400)
          @sum = @sum + temp.price * params[:plsten].to_f
          @hh.push({"name" => temp.name, "value" => temp.price * params[:plsten].to_f})
        end
      end
      
      if params[:cylindr]
        if params[:cylindr200]
          temp = Baum.find_by(label: :cylindr200)
          @sum = @sum + temp.price * params[:plsten].to_f
          @hh.push({"name" => temp.name, "value" => temp.price * params[:plsten].to_f})
        end
        if params[:cylindr240]
          temp = Baum.find_by(label: :cylindr240)
          @sum = @sum + temp.price * params[:plsten].to_f
          @hh.push({"name" => temp.name, "value" => temp.price * params[:plsten].to_f})
        end
        if params[:cylindr260]
          temp = Baum.find_by(label: :cylindr260)
          @sum = @sum + temp.price * params[:plsten].to_f
          @hh.push({"name" => temp.name, "value" => temp.price * params[:plsten].to_f})
        end
        if params[:cylindr300]
          temp = Baum.find_by(label: :cylindr300)
          @sum = @sum + temp.price * params[:plsten].to_f
          @hh.push({"name" => temp.name, "value" => temp.price * params[:plsten].to_f})
        end
      end
       
      if params[:profil]
        if params[:profil150]
          temp = Baum.find_by(label: :profil150)
          @sum = @sum + temp.price * params[:plsten].to_f
          @hh.push({"name" => temp.name, "value" => temp.price * params[:plsten].to_f})
        end
        if params[:profil180]
          temp = Baum.find_by(label: :profil180)
          @sum = @sum + temp.price * params[:plsten].to_f
          @hh.push({"name" => temp.name, "value" => temp.price * params[:plsten].to_f})
        end
        if params[:profil200]
          temp = Baum.find_by(label: :profil200)
          @sum = @sum + temp.price * params[:plsten].to_f
          @hh.push({"name" => temp.name, "value" => temp.price * params[:plsten].to_f})
        end
      end
      
      if params[:profilklei]
        if params[:profil150klei]
          temp = Baum.find_by(label: :profil150klei)
          @sum = @sum + temp.price * params[:plsten].to_f
          @hh.push({"name" => temp.name, "value" => temp.price * params[:plsten].to_f})
        end
        if params[:profil180klei]
          temp = Baum.find_by(label: :profil180klei)
          @sum = @sum + temp.price * params[:plsten].to_f
          @hh.push({"name" => temp.name, "value" => temp.price * params[:plsten].to_f})
        end
        if params[:profil200klei]
          temp = Baum.find_by(label: :profil200klei)
          @sum = @sum + temp.price * params[:plsten].to_f
          @hh.push({"name" => temp.name, "value" => temp.price * params[:plsten].to_f})
        end
        if params[:profil300klei]
          temp = Baum.find_by(label: :profil300klei)
          @sum = @sum + temp.price * params[:plsten].to_f
          @hh.push({"name" => temp.name, "value" => temp.price * params[:plsten].to_f})
        end
      end
    end
    
    #pokraska
    if params[:pokraska]
      temp = Baum.find_by(label: :pokraska)
      @sum = @sum + temp.price * params[:plsten].to_f
      @hh.push({"name" => temp.name, "value" => temp.price * params[:plsten].to_f})
    end
    
       
    
    
    #potolok
    if params[:plpot].to_f > 0
      if params[:vagonka]
      temp = Baum.find_by(label: :vagonka)
      @sum = @sum + temp.price * params[:plsten].to_f
      @hh.push({"name" => temp.name, "value" => temp.price * params[:plpot].to_f})
      end
    end
    
    
    #perekrytie
    if params[:plper].to_f > 0
      temp = Baum.find_by(label: :plper)
      @sum = @sum + temp.price * params[:plper].to_f
      @hh.push({"name" => temp.name, "value" => temp.price * params[:plper].to_f})
      
      if params[:doskasosna]
        temp = Baum.find_by(label: :doskasosna)
        @sum = @sum + temp.price * params[:plper].to_f
        @hh.push({"name" => temp.name, "value" => temp.price * params[:plper].to_f})
      end
      
      if params[:utiplenieper]
        temp = Baum.find_by(label: :utiplenieper)
        @sum = @sum + temp.price * params[:plper].to_f
        @hh.push({"name" => temp.name, "value" => temp.price * params[:plper].to_f})
      end
    end
    
    
    #krovlia
    if params[:plkrov].to_f > 0
      temp = Baum.find_by(label: :stropsistema)
      @sum = @sum + temp.price * params[:plkrov].to_f
      @hh.push({"name" => temp.name, "value" => temp.price * params[:plkrov].to_f})
      
      if params[:bitumkrov]
        temp = Baum.find_by(label: :bitumkrov)
        @sum = @sum + temp.price * params[:plkrov].to_f
        @hh.push({"name" => temp.name, "value" => temp.price * params[:plkrov].to_f})
      end
      if params[:metkrov]
        temp = Baum.find_by(label: :metkrov)
        @sum = @sum + temp.price * params[:plkrov].to_f
        @hh.push({"name" => temp.name, "value" => temp.price * params[:plkrov].to_f})
      end
      if params[:utipleniekrov]
        temp = Baum.find_by(label: :utipleniekrov)
        @sum = @sum + temp.price * params[:plkrov].to_f
        @hh.push({"name" => temp.name, "value" => temp.price * params[:plkrov].to_f})
      end
    end
    
    
    #marketing
    if !(@sum == 0)
      @sum = @sum + Baum.find_by(label: :marketing).price
      @sum = @sum + Baum.find_by(label: :logistika).price
      if params[:akcionka]
        @sum = @sum + Baum.find_by(label: :akcionka).price
      end
      if params[:regional]
        @sum = @sum + Baum.find_by(label: :regional).price
      end
           
      
      if @sum >= Baum.find_by(label: :sum2).price
        @sum = @sum * Baum.find_by(label: :nacenka14).price
      elsif @sum >= Baum.find_by(label: :sum1).price
        @sum = @sum * Baum.find_by(label: :nacenka15).price
      else
        @sum = @sum * Baum.find_by(label: :pribyl).price
      end
      
      
      
    end
  end

  
  
  
  
  private
    def baum_params
      params.require(:baum).permit(:name, :price, :label)
    end
end

app/helpers/baums_helper.rb
module BaumsHelper
end

app/views/baums/edit.html.erb
<%= form_for @baum do |f| %>
 
  <p>
    <strong><%= @baum.name %></strong>
  </p>
 
 <p>
    Цена:<%= f.text_field :price %>
  </p>
  
   
 <p>
    Название:<%= f.text_field :name %>
  </p>
  
    
  <p>
    <%= submit_tag "Сохранить" %>
  </p>
<% end %>

app/views/baums/form.html.erb
<h1 class="h1_form">"СМЕРЕКОВА ХАТА"</h1><br>

<%= form_tag("sum", method: :get, class: "form-horizontal", role: "form") do %>
  Архитектурный проект <%= check_box_tag 'archproject' %><br><br>
  <span class="caption">Фундамент</span><br>
  Площадь <%= number_field_tag 'plfund' %> м<sup>2</sup><br><br>
  
  <span class="caption">Стены</span><br>
  Площадь <%= number_field_tag 'plsten' %> м<sup>2</sup><br><br>
  
  <span class="caption">Тип стен</span><br>
  Дикий сруб <%= check_box_tag 'dikii' %><br>
  Диаметр: 200 <%= check_box_tag 'dikii200' %>, 240 <%= check_box_tag 'dikii240' %>,
           260 <%= check_box_tag 'dikii260' %>, 300 <%= check_box_tag 'dikii300' %>, 
           400 <%= check_box_tag 'dikii400' %> <br><br>
  
  Оцилиндровка <%= check_box_tag 'cylindr' %><br>
  Диаметр: 200 <%= check_box_tag 'cylindr200' %>, 240 <%= check_box_tag 'cylindr240' %>,
           260 <%= check_box_tag 'cylindr260' %>, 300 <%= check_box_tag 'cylindr300' %><br><br>
  
  
  Профилированный <%= check_box_tag 'profil' %><br>
  Толщина: 150 <%= check_box_tag 'profil150' %>, 180 <%= check_box_tag 'profil180' %>,
           200 <%= check_box_tag 'profil200' %><br><br>
           
  Профилированный клееный <%= check_box_tag 'profilklei' %><br>
  Толщина: 150 <%= check_box_tag 'profil150klei' %>, 180 <%= check_box_tag 'profil180klei' %>,
           200 <%= check_box_tag 'profil200klei' %>, 300 <%= check_box_tag 'profil300klei' %><br>
           Сухой лес <%= check_box_tag 'suhoiles' %><br><br>
           
  <span class="caption">Покраска</span> <%= check_box_tag 'pokraska' %><br><br>
  
  <span class="caption">Потолки</span><br>
  Площадь <%= number_field_tag 'plpot' %> м<sup>2</sup><br>
  Отделка потолка: Вагонка <%= check_box_tag 'vagonka' %><br><br>
  
  <span class="caption">Перекрытие</span><br>
  Площадь <%= number_field_tag 'plper' %> м<sup>2</sup><br>
  Отделка: Доска(сосна) <%= check_box_tag 'doskasosna' %><br>
  Утепление <%= check_box_tag 'utiplenieper' %><br><br>
  
  <span class="caption">Кровля</span><br>
  Площадь <%= number_field_tag 'plkrov' %> м<sup>2</sup><br>
  Тип кровли: Битумная <%= check_box_tag 'bitumkrov' %>, Металлочерепица <%= check_box_tag 'metkrov' %><br>
  Утепление <%= check_box_tag 'utipleniekrov' %><br><br>
  
  <span class="caption">Акционная наценка</span> <%= check_box_tag 'akcionka' %><br>
  <span class="caption">Региональный проект</span> <%= check_box_tag 'regional' %><br><br>
    
  
  <%= submit_tag "Подсчитать стоимость", class: "btn btn-xs btn-info" %>
  <%= link_to 'Очистить форму', baums_form_path, class: "btn btn-xs btn-warning" %><br><br>
    <% if can? :update, Baum %>
      <%= link_to 'Перейти в раздел редактирования', baums_path, class: "btn btn-xs btn-info" %>
    <% end %>
<% end %>
<br>
<br>
<br>

app/views/baums/index.html.erb
<h1>Все составляющие строительства проекта "Смерекова хата"</h1>
 <%= link_to "Excel", baums_path(format: "xls") %>
<table class="table table-striped table-hover">
  <tr>
    <th><strong>Название</strong></th>
    <th>Цена за м<sup>2</sup> или %</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
  <% @baums.each do |baum| %>
    <tr>
      <td><%= baum.name %></td>
      <td><%= baum.price %> </td>
      <% if can? :read, Baum %>
       <td><%= link_to 'Подробно..', baum, class: "btn btn-xs btn-info" %></td> 
      <% end %>
      <% if can? :update, Baum %>
         <td><%= link_to 'Редактировать', edit_baum_path(baum), class: "btn btn-xs btn-warning" %></td>
      <% end %>
      <% if can? :destroy, Baum %>
         <td><%= link_to 'Удалить!', baum_path(baum), class: "btn btn-xs btn-danger", 
            method: :delete,
            data: { confirm: 'Вы уверены?' } %></td> 
      <% end %>
    
          
     
    </tr>
  <% end %>
</table>
<br>
<%= link_to 'Добавить новый елемент проекта', new_baum_path, class: "btn btn-sm btn-success" %>
<%= link_to 'Перейти к форме', baums_form_path, class: "btn btn-xs btn-primary" %>
<br>
<br>
<br>

app/views/baums/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Price</Data></Cell>
      </Row>
    <% @baums.each do |baum| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= baum.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= baum.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= baum.price %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/baums/new.html.erb
<h2>Новый елемент проекта</h2>
<%= form_for @baum do |f| %>
 
  <p>
    Название:<%= f.text_field :name %>
  </p>
 
  <p>
    Цена:<%= f.text_field :price %>
  </p>
  
  <p>
    Метка:<%= f.text_field :label %>
  </p> 
  
  <p>
    <%= submit_tag "Создать" %>
  </p>
<% end %>

app/views/baums/show.html.erb
<p>
  <strong>Название:</strong>
  <%= @baum.name %>
</p>

<p>
  <strong>Цена:</strong>
  <%= @baum.price %>
</p>


<%= link_to 'Изменить', edit_baum_path(@baum) %>

app/views/baums/sum.html.erb
<br>Стоимость проекта: <%= @sum %> грн. <br>

<div id="result">
  <% if @hh.length > 0 %>
  <h1>Выходные данные проекта</h1>
  <table class="table table-striped table-hover">
    <tr>
      <th><strong>Название</strong></th>
      <th><strong>Стоимость (грн)</strong></th>
    </tr>
    <% @hh.each do |h| %>
      <tr>
        <td><%= h["name"] %></td>
        <td><%= h["value"] %></td>
      </tr>
    <% end %>
  </table><br>
  <% end %>
</div>