config/routes.rb
Rails.application.routes.draw do
  
  get 'components/index'
  get "elements/form"
  get "elements/sum"
  resources :elements
  
  get "baums/form"
  get "baums/sum"
  resources :baums
  root 'welcome#index'
  
  devise_for :users
  resources :form do
    resources :component
  end
  #resources :welcome
  #get 'welcome/index'
  #get "welcome/sum"
  
  #root "elements#form"


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hausform</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      <div class="navbar-inner">
        <div class="container">
        <ul class="nav  navbar-nav pull-left">
            <% if can? :update, Element %>
              <li class="nav  navbar-nav pull-left"><%= link_to 'ЕвроХауз', elements_path %></li>
              <li class="nav  navbar-nav pull-left"><%= link_to 'СМЕРЕКОВА ХАТА', baums_path %></li>
            <% end %>
          </ul>
        
        
        
        
        
          <ul class="nav  navbar-nav pull-right">
            <% if user_signed_in? %>
              <li><%= link_to "#{current_user.email}", '#' %></li>
              <li><%= link_to 'Изменить пароль', edit_user_registration_path %></li>
              <li><%= link_to 'Выйти', destroy_user_session_path, :method => :delete %></li>
            <% else %>
              <li><%= link_to 'Войти', new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </header>



<div class="container">
  <div class="mycontent">
  
  </div>
  <%= yield %>
</div>


</body>
</html>